name: Unit tests

on:
  push:
    branches:
      - main
      - next
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-node:
    name: Test on Node.js v${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: install
        run: yarn
      - name: run eslint
        run: yarn lint
      - name: run prettylint
        run: yarn prettylint
      - name: run typecheck
        run: yarn typecheck
      - name: run build
        run: yarn build
      - name: run tests
        run: yarn test --coverage
        env:
          CI: true
  test-os:
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: install
        run: yarn
      - name: run prettylint
        run: yarn prettylint
      - name: run typecheck
        run: yarn typecheck
      - name: run build
        run: yarn build
      - name: run tests
        run: yarn test --coverage
        env:
          CI: true
  release:
    if:
      # prettier-ignore
      ${{ github.event_name == 'push' && (github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/next') }}
    needs:
      - test-node
      - test-os
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: install
        run: yarn
      - name: run build
        run: yarn build
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
